### PR TITLE
Fix default left for alignment

### LINKED ISSUE #135: set default character alignment to " left-aligned"
> Text here does need to be left-aligned rather than centre-aligned for easier readability. Also strange that AEDECOD is left-aligned and AETERM is not
https://github.com/insightsengineering/sme-tasks/issues/619#issuecomment-1504842472

### PR DESCRIPTION
**Pull request by Melkiades**
Fixes #135

### CODE REVIEW

File: tests/testthat/test-print.R [hunk 1]
```diff
@@ -118,16 +45,18 @@ testthat::test_that("as_listing produces correct output when default_formatting
...
+      key_cols = "USUBJID",
+      default_formatting = list(numeric = fmt_config(align = "left"))
+    ),
+    regexp = paste0(
+      "Format configurations must be supplied for all listing columns. ",
+      "To cover all remaining columns please add an ",
+      "'all' configuration to `default_formatting`."
+    )
+  ) %>%
+    suppressMessages()
```
Comment (Melkiades) [inline tests/testthat/test-print.R:59]: messages are no more hidden. Do we need the automatic sorting message? @shajoezhu I think yes but I was wondering if there was another option for this

File: R/rlistings.R [hunk 2]
```diff
@@ -173,21 +185,24 @@ as_listing <- function(df,
...
       }
       default_formatting[["all"]]
     }
-    obj_format(df[[col]]) <- slot(col_fmt, "format")
-    obj_na_str(df[[col]]) <- slot(col_fmt, "format_na_str")
-    obj_align(df[[col]]) <- slot(col_fmt, "align")
+    # ANY attr <- fmt_config slot
+    obj_format(df[[col]]) <- obj_format(col_fmt)
+    obj_na_str(df[[col]]) <- if (is.null(obj_na_str(col_fmt))) "NA" else obj_na_str(col_fmt)
+    obj_align(df[[col]]) <- if (is.null(obj_align(col_fmt))) "left" else obj_align(col_fmt)
```
Comment (Melkiades) [inline R/rlistings.R:205]: Change in default (upstream default is `NULL`)

**Review by shajoezhu — APPROVED** [review]
lgtm! Thanks @Melkiades
